<?php

declare(strict_types=1);

return [
    'paper' => [
        'title' => 'Forensic Investigation of Humanoid Social Robot: A Case Study on Zenbo Robot',
        'authors' => [
            'Farkhund Iqbal',
            'Abdullah Kazim',
            'Aine MacDermott',
            'Richard Ikuesan',
            'Musaab Hasan',
            'Andrew Marrington',
        ],
        'year' => 2024,
        'venue' => 'The 19th International Conference on Availability, Reliability and Security',
        'venue_short' => 'ARES 2024',
        'location' => 'Vienna, Austria',
        'dates' => 'July 30-August 02, 2024',
        'publisher' => 'Association for Computing Machinery',
        'series' => 'ACM International Conference Proceeding Series',
        'article_number' => '194',
        'pages' => '9',
        'isbn' => '979-8-4007-1718-5',
        'doi' => '10.1145/3664476.3670906',
        'doi_url' => 'https://doi.org/10.1145/3664476.3670906',
        'acm_url' => 'https://dl.acm.org/doi/10.1145/3664476.3670906',
        'zu_record_url' => 'https://zuscholars.zu.ac.ae/works/6716/',
        'pure_record_url' => 'https://nchr.elsevierpure.com/en/publications/forensic-investigation-of-humanoid-social-robot-a-case-study-on-z/',
        'keywords' => [
            'Digital forensics',
            'Humanoid robot',
            'Internet of Things forensics',
            'Logical acquisition',
            'Zenbo',
            'Android artifacts',
            'Chain of custody',
        ],
        'citation' => 'Iqbal, F., Kazim, A., MacDermott, A., Ikuesan, R., Hasan, M., & Marrington, A. (2024). Forensic Investigation of Humanoid Social Robot: A Case Study on Zenbo Robot. In ARES 2024 - 19th International Conference on Availability, Reliability and Security, Proceedings, Article 194. Association for Computing Machinery. https://doi.org/10.1145/3664476.3670906',
        'summary' => 'The paper presents a case study on Zenbo humanoid robot forensics, showing how logical acquisition, companion app analysis, SHA-256 hash comparison, and artifact correlation can support investigations where a robot may act as a digital witness.',
    ],
    'workflow_stages' => [
        [
            'id' => 'case-authorization',
            'name' => 'Case authorization and scope',
            'purpose' => 'Confirm authority, scope, device ownership, privacy constraints, and examination boundaries.',
            'evidence' => 'Signed authorization, scope statement, device identifiers, examiner assignment, and case objectives.',
        ],
        [
            'id' => 'scene-and-device-record',
            'name' => 'Scene and device record',
            'purpose' => 'Document the humanoid robot, paired devices, network context, power state, and visible user-interface state.',
            'evidence' => 'Photographs, notes, serials, robot name, companion devices, network identifiers, and seizure time.',
        ],
        [
            'id' => 'baseline-image',
            'name' => 'Baseline image and hash set',
            'purpose' => 'Acquire a clean or initial logical image and calculate SHA-256 hashes for future comparison.',
            'evidence' => 'Initial logical acquisition, file inventory, SHA-256 manifest, acquisition tool version, and examiner notes.',
        ],
        [
            'id' => 'controlled-activity',
            'name' => 'Controlled activity or case activity reconstruction',
            'purpose' => 'Capture known interaction scenarios such as calls, reminders, voice responses, app imports, and media events.',
            'evidence' => 'Activity matrix, timestamps, companion app actions, robot actions, and expected artifacts.',
        ],
        [
            'id' => 'final-acquisition',
            'name' => 'Final logical acquisition',
            'purpose' => 'Acquire robot and companion app data using non-destructive logical methods where possible.',
            'evidence' => 'ADB pull result, ADB backup result, companion app package exports, and second SHA-256 manifest.',
        ],
        [
            'id' => 'hash-differencing',
            'name' => 'Hash differencing',
            'purpose' => 'Compare initial and final hash manifests to identify added, removed, and modified files.',
            'evidence' => 'Changed-file report, unchanged-file baseline, modified artifact list, and anomaly notes.',
        ],
        [
            'id' => 'artifact-analysis',
            'name' => 'Artifact analysis and correlation',
            'purpose' => 'Analyze databases, XML preferences, logs, media, packages, and system configuration artifacts.',
            'evidence' => 'Artifact worksheets, parsed tables, timeline fragments, cross-source correlation, and confidence ratings.',
        ],
        [
            'id' => 'forensic-reporting',
            'name' => 'Reporting and peer review',
            'purpose' => 'Produce a repeatable, evidence-backed report with limitations, confidence, and validation notes.',
            'evidence' => 'Forensic report, timeline, chain-of-custody appendix, limitations, and peer-review record.',
        ],
    ],
    'artifact_sources' => [
        [
            'id' => 'zenbo-master-videophone-db',
            'name' => 'Zenbo Master videophone database',
            'source' => 'Zenbo Master companion app',
            'path' => 'asusRobotVideophone.db',
            'category' => 'Companion app database',
            'sensitivity' => 'High',
            'evidentiary_value' => 'User profile, family relationship, linked robot details, call records, notifications, and speak-out command logs.',
            'validation' => 'Correlate call and contact records with robot-side asusRobot.db and notification timestamps.',
            'fields' => ['authority_management_contacts', 'bind_robot_list', 'call_logs', 'contacts', 'notification_center', 'speak_out_log'],
        ],
        [
            'id' => 'zenbo-master-share-pref-offset',
            'name' => 'Zenbo Master server offset preference',
            'source' => 'Zenbo Master companion app',
            'path' => 'share_pref_*.xml',
            'category' => 'XML preference',
            'sensitivity' => 'Medium',
            'evidentiary_value' => 'Server/local time offset that can assist time normalization between local device activity and service time.',
            'validation' => 'Normalize timestamps and compare against known activity records and acquisition time.',
            'fields' => ['server_time_offset', 'local_time_reference', 'file_updated_time'],
        ],
        [
            'id' => 'zenbo-master-share-pref',
            'name' => 'Zenbo Master shared preference record',
            'source' => 'Zenbo Master companion app',
            'path' => 'SHARE_PREF.xml',
            'category' => 'XML preference',
            'sensitivity' => 'High',
            'evidentiary_value' => 'Configured account details and robot name used by the companion app.',
            'validation' => 'Correlate configured robot name with bind_robot_list and robot-side user records.',
            'fields' => ['configured_account', 'robot_name', 'preference_timestamp'],
        ],
        [
            'id' => 'zenbo-master-device-status',
            'name' => 'Zenbo Master device status preferences',
            'source' => 'Zenbo Master companion app',
            'path' => 'battery_*.xml, allSpace*, useSpace*, zenboImageVersion*',
            'category' => 'Device status',
            'sensitivity' => 'Medium',
            'evidentiary_value' => 'Battery level, image version, storage use, and robot status at last app connection.',
            'validation' => 'Compare to robot build artifacts, acquisition notes, and timeline context.',
            'fields' => ['battery_level', 'storage_total', 'storage_used', 'image_version'],
        ],
        [
            'id' => 'zenbo-app-builder-phone',
            'name' => 'Zenbo App Builder smartphone package',
            'source' => 'Zenbo App Builder companion app',
            'path' => 'com.asus.appbuilder.editor',
            'category' => 'Companion app package',
            'sensitivity' => 'Medium',
            'evidentiary_value' => 'The paper reports limited evidentiary value on the smartphone side for linking imported apps to a source device.',
            'validation' => 'Record negative findings clearly and seek correlation from robot-side imported app artifacts.',
            'fields' => ['package_presence', 'negative_finding', 'examiner_note'],
        ],
        [
            'id' => 'blockly-engine-db',
            'name' => 'Zenbo App Builder robot database',
            'source' => 'Zenbo robot',
            'path' => 'BlocklyEngine.db',
            'category' => 'Robot database',
            'sensitivity' => 'High',
            'evidentiary_value' => 'Imported app properties, sequential app IDs, import dates, use dates, app versions, and app names.',
            'validation' => 'Compare highest ID with latest import date and compare database values to BlocklyManifest.xml.',
            'fields' => ['id', 'app_id', 'app_name', 'app_version', 'import_date', 'use_date'],
        ],
        [
            'id' => 'zenbo-script-folder',
            'name' => 'Imported app folder collection',
            'source' => 'Zenbo robot',
            'path' => 'ZenboScriptFolderPlace',
            'category' => 'Imported application content',
            'sensitivity' => 'High',
            'evidentiary_value' => 'Folders for imported apps, app manifest, block definitions, executable script, icon, media, audio, and bundled files.',
            'validation' => 'Compare folder names to BlocklyEngine app_id and inspect bundled files for unauthorized payloads.',
            'fields' => ['BlocklyManifest.xml', 'blocksStack.xml', 'executeScript.html', 'icon.png', 'media_files'],
        ],
        [
            'id' => 'execute-script-html',
            'name' => 'Imported app execution script',
            'source' => 'Zenbo robot',
            'path' => 'executeScript.html',
            'category' => 'Application behavior',
            'sensitivity' => 'High',
            'evidentiary_value' => 'Functional behavior of imported apps and potential malicious automation logic.',
            'validation' => 'Correlate script behavior with blocksStack.xml and observed robot activity.',
            'fields' => ['script_actions', 'resource_references', 'behavior_flow'],
        ],
        [
            'id' => 'blocks-stack-xml',
            'name' => 'Imported app block stack',
            'source' => 'Zenbo robot',
            'path' => 'blocksStack.xml',
            'category' => 'Application behavior',
            'sensitivity' => 'High',
            'evidentiary_value' => 'XML representation of app behavior and possible traces of earlier versions.',
            'validation' => 'Compare with executeScript.html and current manifest to identify behavior changes.',
            'fields' => ['block_actions', 'historical_changes', 'resource_references'],
        ],
        [
            'id' => 'robot-user-profile-db',
            'name' => 'Robot user and relationship database',
            'source' => 'Zenbo robot',
            'path' => 'robot.asus.com.robotprofileprovider/asusRobot.db',
            'category' => 'Robot database',
            'sensitivity' => 'High',
            'evidentiary_value' => 'Configured users, relatives, profile pictures, birthdays, email addresses, gender values, admin flags, and robot-side call logs.',
            'validation' => 'Correlate users and calls with Zenbo Master asusRobotVideophone.db.',
            'fields' => ['user_profile', 'call_logs', 'relative', 'admin_flag', 'profile_picture'],
        ],
        [
            'id' => 'robot-reminder-package',
            'name' => 'Robot reminder package',
            'source' => 'Zenbo robot',
            'path' => 'com.asus.robot.reminder',
            'category' => 'Calendar and tasks',
            'sensitivity' => 'High',
            'evidentiary_value' => 'Calendar entries and to-do records that can support timeline reconstruction.',
            'validation' => 'Compare reminder timestamps with call, notification, and response logs.',
            'fields' => ['calendar_items', 'todo_items', 'reminder_times'],
        ],
        [
            'id' => 'default-voice-command-logs',
            'name' => 'Default voice command response set',
            'source' => 'Zenbo robot',
            'path' => '/sdcard/Logs/DS/AsrSet*',
            'category' => 'Voice response reference',
            'sensitivity' => 'Low',
            'evidentiary_value' => 'Default command/response mappings that may clarify robot capability, but not necessarily user-issued commands.',
            'validation' => 'Confirm presence in baseline image and avoid over-attribution to user activity.',
            'fields' => ['asr_set_file', 'default_command', 'default_response'],
        ],
        [
            'id' => 'created-voice-response-logs',
            'name' => 'Created voice response logs',
            'source' => 'Zenbo robot',
            'path' => '/storage/self/primary/Logs/DS/Record*TtsInfo.txt',
            'category' => 'Voice response evidence',
            'sensitivity' => 'High',
            'evidentiary_value' => 'Daily files containing Zenbo responses to user voice commands.',
            'validation' => 'Correlate file date with other activity records; note absence of per-response timestamps.',
            'fields' => ['file_date', 'response_text', 'chronology_limitation'],
        ],
        [
            'id' => 'storytelling-media',
            'name' => 'Storytelling content',
            'source' => 'Zenbo robot',
            'path' => '/system/media/storytelling',
            'category' => 'Media and scripted content',
            'sensitivity' => 'Medium',
            'evidentiary_value' => 'Built-in stories, images, audio, video, and scripts that may reveal modified behavior or unauthorized recording triggers.',
            'validation' => 'Compare content against known-good baseline and review script references to camera/audio behavior.',
            'fields' => ['story_assets', 'javascript_files', 'media_metadata'],
        ],
        [
            'id' => 'system-app-directories',
            'name' => 'System app directories',
            'source' => 'Zenbo robot',
            'path' => '/system/app and /system/priv-app',
            'category' => 'System packages',
            'sensitivity' => 'Medium',
            'evidentiary_value' => 'APK inventory for core system and privileged background applications.',
            'validation' => 'Compare APK hashes with baseline and installed package records.',
            'fields' => ['apk_path', 'package_name', 'hash', 'extraction_time'],
        ],
        [
            'id' => 'frosting-db',
            'name' => 'Installed package listing',
            'source' => 'Zenbo robot',
            'path' => 'com.android.vending/frosting.db',
            'category' => 'Package inventory',
            'sensitivity' => 'Medium',
            'evidentiary_value' => 'List of installed packages and their actual installation paths.',
            'validation' => 'Correlate with /system/app, /system/priv-app, and extracted APK metadata.',
            'fields' => ['package_name', 'installed_path', 'package_record'],
        ],
        [
            'id' => 'build-prop',
            'name' => 'Build properties',
            'source' => 'Zenbo robot',
            'path' => 'build.prop',
            'category' => 'System configuration',
            'sensitivity' => 'Low',
            'evidentiary_value' => 'Android version, ASUS version, preferred network type, and last security patch.',
            'validation' => 'Compare to acquisition notes, device version preferences, and package inventory.',
            'fields' => ['android_version', 'asus_version', 'security_patch', 'network_type'],
        ],
        [
            'id' => 'cpu-accounting',
            'name' => 'CPU accounting files',
            'source' => 'Zenbo robot',
            'path' => '/acct/cpuacct.usage, /acct/cpuacct.stat, /acct/cpuacct.usage_percpu',
            'category' => 'Runtime activity',
            'sensitivity' => 'Medium',
            'evidentiary_value' => 'CPU uptime and processing details that can help validate event timing and device operation.',
            'validation' => 'Compare with kernel logs, acquisition timestamps, and reported uptime.',
            'fields' => ['cpu_usage', 'cpu_stat', 'per_cpu_usage'],
        ],
        [
            'id' => 'kernel-and-diagnostic-logs',
            'name' => 'Kernel and diagnostic logs',
            'source' => 'Zenbo robot',
            'path' => '/sdcard/Logs/last_kernel_logs and related logs',
            'category' => 'System logs',
            'sensitivity' => 'High',
            'evidentiary_value' => 'Kernel, diagnostic, event, and server-debugging logs that may record actions and timing.',
            'validation' => 'Normalize timestamps and correlate with application-level records.',
            'fields' => ['kernel_message', 'event_tag', 'server_debug_entry', 'timestamp'],
        ],
        [
            'id' => 'dcim-download-media',
            'name' => 'Robot media directories',
            'source' => 'Zenbo robot',
            'path' => 'DCIM and Download',
            'category' => 'Media evidence',
            'sensitivity' => 'High',
            'evidentiary_value' => 'Images, videos, and downloaded files stored on or captured by the robot.',
            'validation' => 'Analyze metadata, camera profile compatibility, hashes, and timeline context.',
            'fields' => ['filename', 'media_type', 'metadata', 'hash'],
        ],
        [
            'id' => 'camera-profiles',
            'name' => 'Camera configuration profiles',
            'source' => 'Zenbo robot',
            'path' => '/system/etc/camera*.xml and camera_ddr.sh',
            'category' => 'Device capability',
            'sensitivity' => 'Low',
            'evidentiary_value' => 'Camera resolution and supported image-size details that can help attribute or exclude images.',
            'validation' => 'Compare image metadata to supported camera profile values.',
            'fields' => ['resolution', 'camera_profile', 'supported_size'],
        ],
        [
            'id' => 'audio-profiles',
            'name' => 'Audio configuration profiles',
            'source' => 'Zenbo robot',
            'path' => '/system/etc/audio_effects.conf and audio_policy.conf',
            'category' => 'Device capability',
            'sensitivity' => 'Low',
            'evidentiary_value' => 'Audio policy and effect configuration that can support capability analysis.',
            'validation' => 'Compare audio evidence and system behavior with configured audio policies.',
            'fields' => ['audio_policy', 'effect_profile', 'route'],
        ],
        [
            'id' => 'recent-documents-db',
            'name' => 'Recent documents database',
            'source' => 'Zenbo robot',
            'path' => 'com.android.documentsui/recent.db',
            'category' => 'Usage timeline',
            'sensitivity' => 'Medium',
            'evidentiary_value' => 'Timestamps for app or document use that can strengthen a timeline.',
            'validation' => 'Correlate with reminders, package records, and logs.',
            'fields' => ['recent_item', 'last_used_time', 'source_package'],
        ],
        [
            'id' => 'photos-databases',
            'name' => 'Photo app databases',
            'source' => 'Zenbo robot',
            'path' => 'com.google.android.apps.photos/gphotos0.db and local_trash.db',
            'category' => 'Media evidence',
            'sensitivity' => 'High',
            'evidentiary_value' => 'Photo storage locations and deleted photo references.',
            'validation' => 'Correlate with DCIM, Download, media metadata, and deletion timeline.',
            'fields' => ['photo_path', 'trash_path', 'deleted_indicator'],
        ],
        [
            'id' => 'settings-provider',
            'name' => 'Android settings provider',
            'source' => 'Zenbo robot',
            'path' => 'com.android.providers.settings',
            'category' => 'System configuration',
            'sensitivity' => 'Medium',
            'evidentiary_value' => 'Screen brightness, auto-time, notification, Wi-Fi access point, and USB mass-storage settings.',
            'validation' => 'Compare with acquisition context, network state, and device usage timeline.',
            'fields' => ['brightness', 'auto_time', 'wifi_notification', 'usb_mass_storage'],
        ],
    ],
    'forensic_challenges' => [
        [
            'id' => 'distributed-evidence',
            'name' => 'Distributed evidence across robot, companion app, and network context',
            'severity' => 'High',
            'description' => 'The paper highlights that full IoT forensic trails require piecing together artifacts from multiple locations.',
            'controls' => ['multi-source-inventory', 'cross-source-correlation', 'timeline-normalization'],
        ],
        [
            'id' => 'logical-only-limits',
            'name' => 'Logical acquisition limitations',
            'severity' => 'High',
            'description' => 'Non-intrusive acquisition preserves integrity but may not expose deleted content or protected directories directly.',
            'controls' => ['non-intrusive-first', 'adb-method-record', 'limitations-register'],
        ],
        [
            'id' => 'root-restricted-data',
            'name' => 'Root-restricted application data',
            'severity' => 'High',
            'description' => 'The paper notes that ADB pull cannot extract /data/data application data without elevated access, requiring alternative logical methods.',
            'controls' => ['adb-backup-workflow', 'artifact-prioritization', 'tool-output-validation'],
        ],
        [
            'id' => 'timestamp-friction',
            'name' => 'Timestamp normalization and missing timestamps',
            'severity' => 'Medium',
            'description' => 'Server offsets, local device time, folder extraction times, and missing per-response timestamps require careful interpretation.',
            'controls' => ['timeline-normalization', 'server-offset-review', 'confidence-rating'],
        ],
        [
            'id' => 'negative-network-traces',
            'name' => 'Absent network identifiers',
            'severity' => 'Medium',
            'description' => 'The paper reports that some app and robot packages did not expose source IP addresses or smartphone identifiers.',
            'controls' => ['negative-finding-record', 'cross-source-correlation', 'network-context-note'],
        ],
        [
            'id' => 'sensitive-personal-data',
            'name' => 'Sensitive personal and household data',
            'severity' => 'High',
            'description' => 'Humanoid robots may hold user profiles, relatives, media, reminders, and interaction history.',
            'controls' => ['privacy-minimization', 'evidence-encryption', 'role-based-review'],
        ],
        [
            'id' => 'artifact-tampering',
            'name' => 'Artifact tampering and version mismatch',
            'severity' => 'High',
            'description' => 'Imported app IDs, import dates, manifests, scripts, and block stacks must be compared for consistency.',
            'controls' => ['hash-differencing', 'manifest-consistency-check', 'script-behavior-review'],
        ],
        [
            'id' => 'tool-repeatability',
            'name' => 'Tool repeatability and forensic defensibility',
            'severity' => 'High',
            'description' => 'The methodology uses established forensic tools and hash comparison to support defensible results.',
            'controls' => ['tool-version-record', 'multi-tool-validation', 'peer-review'],
        ],
    ],
    'forensic_controls' => [
        ['id' => 'case-authorization', 'name' => 'Document case authority and scope', 'category' => 'Governance', 'weight' => 8],
        ['id' => 'chain-of-custody', 'name' => 'Maintain chain-of-custody events', 'category' => 'Evidence handling', 'weight' => 9],
        ['id' => 'scene-documentation', 'name' => 'Capture scene, device, and network context', 'category' => 'Evidence handling', 'weight' => 7],
        ['id' => 'multi-source-inventory', 'name' => 'Inventory robot, smartphone, app, and network evidence sources', 'category' => 'Scoping', 'weight' => 9],
        ['id' => 'non-intrusive-first', 'name' => 'Prioritize non-intrusive acquisition methods', 'category' => 'Acquisition', 'weight' => 8],
        ['id' => 'adb-method-record', 'name' => 'Record ADB pull and backup method details', 'category' => 'Acquisition', 'weight' => 8],
        ['id' => 'adb-backup-workflow', 'name' => 'Use logical backup workflow for protected app data where available', 'category' => 'Acquisition', 'weight' => 7],
        ['id' => 'baseline-hash-set', 'name' => 'Create baseline SHA-256 hash manifest', 'category' => 'Integrity', 'weight' => 10],
        ['id' => 'final-hash-set', 'name' => 'Create final SHA-256 hash manifest', 'category' => 'Integrity', 'weight' => 10],
        ['id' => 'hash-differencing', 'name' => 'Compare baseline and final hashes to isolate changed artifacts', 'category' => 'Integrity', 'weight' => 10],
        ['id' => 'tool-version-record', 'name' => 'Record forensic tool versions and settings', 'category' => 'Validation', 'weight' => 7],
        ['id' => 'multi-tool-validation', 'name' => 'Validate findings across more than one forensic tool where practical', 'category' => 'Validation', 'weight' => 8],
        ['id' => 'tool-output-validation', 'name' => 'Validate tool output against manual artifact review', 'category' => 'Validation', 'weight' => 7],
        ['id' => 'artifact-prioritization', 'name' => 'Prioritize high-value artifact sources before deep review', 'category' => 'Analysis', 'weight' => 7],
        ['id' => 'cross-source-correlation', 'name' => 'Correlate robot-side and companion-app artifacts', 'category' => 'Analysis', 'weight' => 9],
        ['id' => 'timeline-normalization', 'name' => 'Normalize timestamps across device, server offset, and acquisition time', 'category' => 'Timeline', 'weight' => 9],
        ['id' => 'server-offset-review', 'name' => 'Review server/local time offset preferences', 'category' => 'Timeline', 'weight' => 6],
        ['id' => 'manifest-consistency-check', 'name' => 'Compare imported app database, manifest, script, and folder values', 'category' => 'Application analysis', 'weight' => 9],
        ['id' => 'script-behavior-review', 'name' => 'Review imported app scripts and block stacks for risky behavior', 'category' => 'Application analysis', 'weight' => 9],
        ['id' => 'media-metadata-review', 'name' => 'Analyze media metadata and camera profile compatibility', 'category' => 'Media analysis', 'weight' => 7],
        ['id' => 'negative-finding-record', 'name' => 'Document negative findings and attribution limits', 'category' => 'Reporting', 'weight' => 6],
        ['id' => 'network-context-note', 'name' => 'Document network context even when package records lack IP traces', 'category' => 'Reporting', 'weight' => 5],
        ['id' => 'privacy-minimization', 'name' => 'Minimize exposure of personal and household data', 'category' => 'Privacy', 'weight' => 8],
        ['id' => 'evidence-encryption', 'name' => 'Encrypt evidence storage and exports', 'category' => 'Privacy', 'weight' => 8],
        ['id' => 'role-based-review', 'name' => 'Restrict sensitive artifact review by role', 'category' => 'Privacy', 'weight' => 6],
        ['id' => 'limitations-register', 'name' => 'Maintain a limitations and assumptions register', 'category' => 'Reporting', 'weight' => 7],
        ['id' => 'confidence-rating', 'name' => 'Assign confidence ratings to findings', 'category' => 'Reporting', 'weight' => 7],
        ['id' => 'peer-review', 'name' => 'Perform independent review before report release', 'category' => 'Reporting', 'weight' => 8],
    ],
    'report_dimensions' => [
        'source_integrity',
        'acquisition_defensibility',
        'artifact_relevance',
        'timeline_quality',
        'cross_source_corroboration',
        'privacy_handling',
        'limitations_and_confidence',
    ],
];

